# Bagging

## custom Bagging

### classification

In [229]:
from sklearn.datasets import make_classification

X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,n_redundant=1)

In [230]:
X

array([[-1.3166271 ,  0.34715814,  0.38875155, ..., -0.96704627,
        -0.5636604 ,  0.30134494],
       [ 1.83719119, -0.09328333,  0.9781736 , ...,  0.07959886,
         1.90509848,  1.24937447],
       [-0.68646754,  0.72348334, -0.4519062 , ...,  1.27439476,
        -0.43383835, -0.6207831 ],
       ...,
       [-0.6236678 , -0.56183879, -1.98822426, ...,  0.36881774,
         1.62668849,  1.03014001],
       [ 1.11970603,  0.65373539,  0.97642316, ..., -1.52189571,
         0.65847105,  0.84314876],
       [-0.13832914,  0.52601147,  1.39140147, ..., -0.38412266,
        -1.41771961, -1.28389306]])

In [231]:
y

array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,

In [232]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [233]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [234]:
tree_clf=DecisionTreeClassifier()
nb_clf=GaussianNB()
lr_clf=LogisticRegression()
svm_clf=SVC(kernel='rbf')

In [235]:
from sklearn.ensemble import VotingClassifier

In [236]:
ensemble=VotingClassifier(estimators=[('tree',tree_clf),('naive_bayes',nb_clf),('regression',lr_clf),('svm',svm_clf)],voting='hard')

In [237]:
ensemble.fit(X_train,y_train)

VotingClassifier(estimators=[('tree', DecisionTreeClassifier()),
                             ('naive_bayes', GaussianNB()),
                             ('regression', LogisticRegression()),
                             ('svm', SVC())])

In [238]:
y_pred=ensemble.predict(X_test)

In [239]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [240]:
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.90      0.91      0.90       151
           1       0.91      0.90      0.90       149

    accuracy                           0.90       300
   macro avg       0.90      0.90      0.90       300
weighted avg       0.90      0.90      0.90       300

0.9033333333333333
[[137  14]
 [ 15 134]]


### Regression

In [241]:
from sklearn.datasets import make_regression


In [242]:
X,y=make_regression(n_samples=100,n_features=10,noise=0.1,random_state=20,n_targets=1)

In [243]:
X.shape

(100, 10)

In [244]:
y.shape

(100,)

In [245]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [246]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR

In [247]:
lr_rgr=LinearRegression()
dt_rgr=DecisionTreeRegressor()
svm_rgr=SVR(kernel='linear')

In [248]:
from sklearn.ensemble import VotingRegressor

In [249]:
ensemble_regression=VotingRegressor(estimators=[('LinearRegression',lr_rgr),('DecisionTreeRegressor',dt_rgr),('SVR',svm_rgr)])

In [250]:
ensemble_regression.fit(X_train,y_train)

VotingRegressor(estimators=[('LinearRegression', LinearRegression()),
                            ('DecisionTreeRegressor', DecisionTreeRegressor()),
                            ('SVR', SVR(kernel='linear'))])

In [251]:
y_pred=ensemble_regression.predict(X_test)

In [252]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7766516337870188

## Multiple model training , pipeline and column transformer

In [253]:
import seaborn as sns

In [254]:
df=sns.load_dataset('tips')

In [255]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [256]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [257]:
print(df.day.unique)

<bound method Series.unique of 0       Sun
1       Sun
2       Sun
3       Sun
4       Sun
       ... 
239     Sat
240     Sat
241     Sat
242     Sat
243    Thur
Name: day, Length: 244, dtype: category
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']>


In [258]:
X= df.drop(columns='day',axis=1)
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
df["day"]=encoder.fit_transform(df['day'])

y=df['day']

In [259]:
X

total_bill   tip     sex smoker    time  size
0         16.99  1.01  Female     No  Dinner     2
1         10.34  1.66    Male     No  Dinner     3
2         21.01  3.50    Male     No  Dinner     3
3         23.68  3.31    Male     No  Dinner     2
4         24.59  3.61  Female     No  Dinner     4
..          ...   ...     ...    ...     ...   ...
239       29.03  5.92    Male     No  Dinner     3
240       27.18  2.00  Female    Yes  Dinner     2
241       22.67  2.00    Male    Yes  Dinner     2
242       17.82  1.75    Male     No  Dinner     2
243       18.78  3.00  Female     No  Dinner     2

[244 rows x 6 columns]

In [260]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No    2  Dinner     2
1       10.34  1.66    Male     No    2  Dinner     3
2       21.01  3.50    Male     No    2  Dinner     3
3       23.68  3.31    Male     No    2  Dinner     2
4       24.59  3.61  Female     No    2  Dinner     4

In [261]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [262]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer


In [263]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No    2  Dinner     2
1       10.34  1.66    Male     No    2  Dinner     3
2       21.01  3.50    Male     No    2  Dinner     3
3       23.68  3.31    Male     No    2  Dinner     2
4       24.59  3.61  Female     No    2  Dinner     4

In [264]:
cat_cols=['sex','smoker','time']
num_cols=['total_bill','tip','size']

In [265]:
# feature engineering automation

num_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy='median')),('scaling',StandardScaler())])

cat_pipeline=Pipeline(steps=[('imputation',SimpleImputer(strategy='most_frequent')),('encoding',OneHotEncoder())])

In [266]:
preprocessor=ColumnTransformer([('num_pipeline',num_pipeline,num_cols),('cat_pipeline',cat_pipeline,cat_cols)])

In [267]:
X_train=preprocessor.fit_transform(X_train)

In [268]:
X_test=preprocessor.transform(X_test)

In [269]:
X_test.shape,X_train.shape

((49, 9), (195, 9))

In [270]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [271]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

models={'tree':DecisionTreeClassifier(),'linear_model':LogisticRegression(),'forest':RandomForestClassifier()}

In [272]:
# function for automation of evaluation

def func(X_train,y_train,X_test,y_test,models):
    evaluation={}
    for i in range(len(models)):
        model=list(models.values())[i]
        model.fit(X_train,y_train)
        y_pred=model.predict(X_test)
        model_score=accuracy_score(y_test,y_pred)
        evaluation[list(models.keys())[i]]=model_score
    return evaluation

In [273]:
func(X_train,y_train,X_test,y_test,models)

{'tree': 0.46938775510204084,
 'linear_model': 0.5510204081632653,
 'forest': 0.5510204081632653}

# Boosting


In [274]:
from sklearn.datasets import make_classification
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier

In [275]:
X,y = make_classification(n_samples=500,n_features=10,n_classes=2,n_redundant=1)

In [276]:
y

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1,

In [277]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [278]:
ada=AdaBoostClassifier()

In [279]:
ada

AdaBoostClassifier()

In [280]:
ada.fit(X_train,y_train)

c:\Users\prithvi\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoostClassifier()

In [281]:
y_pred=ada.predict(X_test)

In [282]:
confusion_matrix(y_test,y_pred)

array([[64,  5],
       [ 9, 72]])

In [283]:
accuracy_score(y_test,y_pred)

0.9066666666666666

In [284]:
gdc=GradientBoostingClassifier()

In [285]:
gdc.fit(X_train,y_train)

GradientBoostingClassifier()

In [286]:
y_pred=gdc.predict(X_test)

In [287]:
accuracy_score(y_test,y_pred)

0.94

In [288]:
from sklearn.datasets import make_regression

In [289]:
X,y=make_regression(n_samples=500,n_features=10,noise=10,random_state=1)

In [290]:
y.shape

(500,)

In [291]:
from sklearn.ensemble import AdaBoostRegressor,GradientBoostingRegressor

In [292]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [293]:
adr=AdaBoostRegressor()
adr.fit(X_train,y_train)
y_pred=adr.predict(X_test)
r2_score(y_test,y_pred)

0.739375379315994

In [294]:
gbr=GradientBoostingRegressor()
gbr.fit(X_train,y_train)
y_pred=gbr.predict(X_test)
r2_score(y_test,y_pred)

0.881311270644365

In [295]:
from xgboost import XGBRFRegressor

xgbr=XGBRFRegressor()

xgbr.fit(X_train,y_train)
y_pred=xgbr.predict(X_test)
r2_score(y_test,y_pred)

0.713967891255096

In [296]:
from xgboost import XGBRFClassifier
xgbc=XGBRFClassifier()
xgbc

XGBRFClassifier(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bytree=None, device=None,
                early_stopping_rounds=None, enable_categorical=False,
                eval_metric=None, feature_types=None, gamma=None,
                grow_policy=None, importance_type=None,
                interaction_constraints=None, max_bin=None,
                max_cat_threshold=None, max_cat_to_onehot=None,
                max_delta_step=None, max_depth=None, max_leaves=None,
                min_child_weight=None, missing=nan, monotone_constraints=None,
                multi_strategy=None, n_estimators=None, n_jobs=None,
                num_parallel_tree=None, objective='binary:logistic',
                random_state=None, reg_alpha=None, ...)

In [297]:
X,y = make_classification(n_samples=500,n_features=10,n_classes=2,n_redundant=1)

In [298]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [299]:
xgbc.fit(X_train,y_train)

XGBRFClassifier(base_score=None, booster=None, callbacks=None,
                colsample_bylevel=None, colsample_bytree=None, device=None,
                early_stopping_rounds=None, enable_categorical=False,
                eval_metric=None, feature_types=None, gamma=None,
                grow_policy=None, importance_type=None,
                interaction_constraints=None, max_bin=None,
                max_cat_threshold=None, max_cat_to_onehot=None,
                max_delta_step=None, max_depth=None, max_leaves=None,
                min_child_weight=None, missing=nan, monotone_constraints=None,
                multi_strategy=None, n_estimators=None, n_jobs=None,
                num_parallel_tree=None, objective='binary:logistic',
                random_state=None, reg_alpha=None, ...)

In [300]:
y_pred=xgbc.predict(X_test)

In [301]:
accuracy_score(y_test,y_pred)

0.9266666666666666

# KNN classifier >>> K Nearest Neighbour

In [302]:
from sklearn.neighbors import KNeighborsClassifier
knnc=KNeighborsClassifier()

In [303]:
knnc.fit(X_train,y_train)
y_pres=knnc.predict(X_test)
accuracy_score(y_test,y_pred)

0.9266666666666666

In [304]:
parameter={"weights":['uniform','distance'],
           'algorithm':['ball_tree',"kd_tree","brute"],
           'leaf_size':[30,10,15,20,7],
           "n_neighbors":[3,5,7,9,10]}

In [305]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=knnc,param_grid=parameter,cv=3,verbose=3)

In [306]:
grid

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [30, 10, 15, 20, 7],
                         'n_neighbors': [3, 5, 7, 9, 10],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [307]:
grid.fit(X_train,y_train)

Fitting 3 folds for each of 150 candidates, totalling 450 fits
[CV 1/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=3, weights=uniform;, score=0.906 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=3, weights=uniform;, score=0.863 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=3, weights=uniform;, score=0.897 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=3, weights=distance;, score=0.906 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=3, weights=distance;, score=0.863 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=3, weights=distance;, score=0.897 total time=   0.0s
[CV 1/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=5, weights=uniform;, score=0.915 total time=   0.0s
[CV 2/3] END algorithm=ball_tree, leaf_size=30, n_neighbors=5, weights=uniform;, score=0.889 total time=   0.0s
[CV 3/3] END algorithm=ball_tree, leaf

GridSearchCV(cv=3, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [30, 10, 15, 20, 7],
                         'n_neighbors': [3, 5, 7, 9, 10],
                         'weights': ['uniform', 'distance']},
             verbose=3)

In [308]:
grid.best_estimator_

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=9)

In [309]:
grid.best_params_

{'algorithm': 'ball_tree',
 'leaf_size': 30,
 'n_neighbors': 9,
 'weights': 'uniform'}

In [310]:
y_pred=grid.predict(X_test)
accuracy_score(y_test,y_pred)

0.8666666666666667